name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # todos los días a medianoche UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Update year progress in README
      run: node index.js

    - name: Commit changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git commit -am "bot: update year progress" || echo "No changes to commit"
        git push
