name: Progress Bar CI

on:
  schedule:
    - cron: "0 0 * * *" # Cada día a medianoche UTC
  workflow_dispatch: # Permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run progress bar script
        run: node index.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update year progress" || exit 0
          git push origin HEAD:main